Stick to ckeditor 4.x
NoMethodError: undefined method `assets_languages=' for Ckeditor:Module
Did you mean?  asset_path=
/usr/local/bundle/bundler/gems/rademade_admin-188e5bf630a6/config/initializers/ckeditor.rb:2:in `block in <top (required)>'